version: "3.7"
services:
  mysql:
    image: mysql:8.0
    container_name: docker_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=Ilia_24998
      - MYSQL_DATABASE=microservice_rent
      - MYSQL_USER=ilya
      - MYSQL_PASSWORD=secret
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 30s 
      interval: 30s
    restart: always

  rent:
    image: rent_service
    container_name: docker_rent
    depends_on:
      - mysql
    ports:
      - "50001:50001"
    command: wait-for-it.sh mysql:3306 && java -jar Rent-1.0.jar
    restart: always