version: '2'
services:
  mysql:
    image: mysql:8.0
    container_name: docker_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=Ilia_24998
      - MYSQL_DATABASE=microservice_rent
      - MYSQL_USER=ilya
      - MYSQL_PASSWORD=secret
    ports:
      - "3308:3306"
    restart: always

  rent:
    image: rent_service
    container_name: docker_rent
    build: ./
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/m2:/root/.m2
    environment:
      WAIT_HOST: mysql:3306
    depends_on:
      - mysql
    restart: always
    expose:
      - 50001