version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: docker_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=Ilia_24998
      - MYSQL_DATABASE=microservice_rent
      - MYSQL_USER=ilya
      - MYSQL_PASSWORD=secret
    ports:
      - "3308:3306"
    restart: always

  rent:
    image: rent_service
    container_name: docker_rent
    environment:
      WAIT_HOSTS: mysql:3306
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/m2:/root/.m2
    depends_on:
      - mysql
    expose:
      - "50001"
    ports:
      - "50001:50001"   
    command: mvn clean spring-boot:run -Dspring-boot.profiles=docker
    restart: always