spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_rent?useUnicode=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ilya
    password: secret
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: create-drop
server:
  port: 50001

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://mysql:3306/microservice_rent?useUnicode=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ilya
    password: secret
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: create-drop
server:
  port: 50001